"""empty message

Revision ID: 0533469e9a82
Revises: 518543b6d90f
Create Date: 2022-10-28 19:17:26.373931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0533469e9a82'
down_revision = '518543b6d90f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tripghana',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('course', 'budget')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('budget', sa.VARCHAR(), nullable=True))
    op.drop_table('tripghana')
    # ### end Alembic commands ###
