"""empty message

Revision ID: 50960334bb52
Revises: e573242dd2c8
Create Date: 2022-09-18 12:43:44.870105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50960334bb52'
down_revision = 'e573242dd2c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('email', sa.String(), nullable=True))
    op.drop_column('course', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('name', sa.VARCHAR(), nullable=False))
    op.drop_column('course', 'email')
    # ### end Alembic commands ###
