"""empty message

Revision ID: 518543b6d90f
Revises: 9a95da9c28ed
Create Date: 2022-10-25 17:28:08.954441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '518543b6d90f'
down_revision = '9a95da9c28ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('review', sa.String(), nullable=True))
    op.drop_column('review', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('name', sa.VARCHAR(), nullable=True))
    op.drop_column('review', 'review')
    # ### end Alembic commands ###
