"""empty message

Revision ID: 57f71f1f0ee6
Revises: 197c042172c1
Create Date: 2022-10-13 18:07:28.273124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57f71f1f0ee6'
down_revision = '197c042172c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'course', ['name'])
    op.create_unique_constraint(None, 'course', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'course', type_='unique')
    op.drop_constraint(None, 'course', type_='unique')
    # ### end Alembic commands ###
