"""empty message

Revision ID: 79a2dfa47287
Revises: f241a8b4e5a9
Create Date: 2022-10-23 18:36:30.947268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79a2dfa47287'
down_revision = 'f241a8b4e5a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'course', ['email'])
    op.drop_column('course', 'name')
    op.drop_column('item', 'incase')
    op.drop_column('item', 'des')
    op.drop_column('item', 'image_file')
    op.add_column('src', sa.Column('hostel', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('src', 'hostel')
    op.add_column('item', sa.Column('image_file', sa.VARCHAR(), nullable=True))
    op.add_column('item', sa.Column('des', sa.VARCHAR(), nullable=True))
    op.add_column('item', sa.Column('incase', sa.VARCHAR(), nullable=True))
    op.add_column('course', sa.Column('name', sa.VARCHAR(), nullable=True))
    op.drop_constraint(None, 'course', type_='unique')
    # ### end Alembic commands ###
