"""empty message

Revision ID: 9463a7073b68
Revises: 323282d4698c
Create Date: 2022-10-23 18:46:35.972362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9463a7073b68'
down_revision = '323282d4698c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'course', ['email'])
    op.drop_column('course', 'name')
    op.drop_column('item', 'image_file')
    op.drop_column('item', 'des')
    op.drop_column('item', 'incase')
    op.add_column('src', sa.Column('hostel', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('src', 'hostel')
    op.add_column('item', sa.Column('incase', sa.VARCHAR(), nullable=True))
    op.add_column('item', sa.Column('des', sa.VARCHAR(), nullable=True))
    op.add_column('item', sa.Column('image_file', sa.VARCHAR(), nullable=True))
    op.add_column('course', sa.Column('name', sa.VARCHAR(), nullable=True))
    op.drop_constraint(None, 'course', type_='unique')
    # ### end Alembic commands ###
