"""empty message

Revision ID: b69a7ebc0339
Revises: 9463a7073b68
Create Date: 2022-10-23 19:04:47.348638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b69a7ebc0339'
down_revision = '9463a7073b68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'course', ['email'])
    op.drop_column('course', 'name')
    op.drop_column('item', 'des')
    op.drop_column('item', 'image_file')
    op.drop_column('item', 'incase')
    op.add_column('src', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('src', 'name')
    op.add_column('item', sa.Column('incase', sa.VARCHAR(), nullable=True))
    op.add_column('item', sa.Column('image_file', sa.VARCHAR(), nullable=True))
    op.add_column('item', sa.Column('des', sa.VARCHAR(), nullable=True))
    op.add_column('course', sa.Column('name', sa.VARCHAR(), nullable=True))
    op.drop_constraint(None, 'course', type_='unique')
    # ### end Alembic commands ###
