"""empty message

Revision ID: e573242dd2c8
Revises: 6fb05acf7e60
Create Date: 2022-09-11 13:48:04.113999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e573242dd2c8'
down_revision = '6fb05acf7e60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('comment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'comment')
    # ### end Alembic commands ###
