"""empty message

Revision ID: fcfb0e817d70
Revises: 0533469e9a82
Create Date: 2023-01-18 13:44:20.602367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcfb0e817d70'
down_revision = '0533469e9a82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('studenthalls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studentName', sa.String(), nullable=True),
    sa.Column('regno', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('program', sa.String(), nullable=True),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hallname', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('studenthalls')
    # ### end Alembic commands ###
